/**
 * Golden fixture tests: replay real recorded Dinkster WS streams
 * (fixtures/events/dinkster-streams.json, generated by running the real Dinkster
 * engine + engine_event_to_wire at backend commit 230ab1a) through
 * DinksterNormalizer and hold it to the contract guards:
 *
 * - every execution event routes by job identity (jobId -> ExecutionRef),
 *   never "the active tab"; unroutable events are dropped, not guessed
 * - success/cached streams terminate with exactly ONE 'completed' even though
 *   the wire carries both run_finished and job_state completed
 * - node_skipped is a NORMAL state with root provenance (origin), and a skip
 *   cascade produces zero error events on bystanders
 * - a fail-policy absence fails the JOB with no node_failed event: the error
 *   carries the culprit node, which must still be marked
 * - progress normalizes to bounded per-node values, previews decode from
 *   self-describing binary frames (4-byte BE header length + JSON + blob)
 * - concurrent jobs interleaved on one socket never cross-route
 * - completed-job hydration (nodeStatesFromDinksterJob) reconstructs per-node
 *   state from a fetched job record for frozen views after reload
 */
import { readFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { asConnectionId, asPromptId, executionKey } from '../src/ids.js'
import {
  DinksterNormalizer,
  decodeDinksterBinaryFrame,
  nodeStatesFromDinksterJob,
  type DinksterJobWire,
  type DinksterRawJson,
  type DinksterRawMessage,
} from '../src/events/dinkster.js'
import { isExecutionEvent, type NodeProgress, type NormalizedEvent } from '../src/events/contract.js'
import { compositorStateOf } from '../src/compositor.js'

interface RecordedMessage extends Record<string, unknown> {
  readonly type: string
  readonly _binary?: boolean
  readonly _blobBase64?: string
}

interface RecordedStream {
  readonly job: DinksterJobWire & Record<string, unknown>
  readonly messages: readonly RecordedMessage[]
}

const fixturePath = join(
  dirname(fileURLToPath(import.meta.url)),
  '../fixtures/events/dinkster-streams.json',
)
const fixture = JSON.parse(readFileSync(fixturePath, 'utf8')) as {
  streams: readonly RecordedStream[]
}
// Generator order: success, cached, skip-cascade, failure.
const [successStream, cachedStream, skipStream, failureStream] = fixture.streams as [
  RecordedStream,
  RecordedStream,
  RecordedStream,
  RecordedStream,
]

const CONN = asConnectionId('conn-test')
const keyOf = (jobId: string): string =>
  executionKey({ connection: CONN, prompt: asPromptId(jobId) })

/** Rebuild the exact wire frame the server would send for one message. */
function toWire(m: RecordedMessage): DinksterRawMessage {
  if (m._binary !== true) return m as DinksterRawJson
  const { _binary, _blobBase64, ...header } = m
  const headerBytes = new TextEncoder().encode(JSON.stringify(header))
  const blob = Uint8Array.from(atob(_blobBase64 ?? ''), (c) => c.charCodeAt(0))
  const frame = new Uint8Array(4 + headerBytes.length + blob.length)
  new DataView(frame.buffer).setUint32(0, headerBytes.length, false)
  frame.set(headerBytes, 4)
  frame.set(blob, 4 + headerBytes.length)
  return frame.buffer
}

function replay(messages: readonly RecordedMessage[]): NormalizedEvent[] {
  const normalizer = new DinksterNormalizer(CONN, () => 0)
  const out: NormalizedEvent[] = []
  for (const m of messages) out.push(...normalizer.normalize(toWire(m)))
  return out
}

const nodeEntries = (events: readonly NormalizedEvent[]): [string, NodeProgress][] =>
  events.flatMap((e) => (e.kind === 'nodeStates' ? Object.entries(e.nodes) : []))

describe('dinkster region lifecycle events', () => {
  it('normalizes the served region event identifiers and payloads', () => {
    const events = replay([
      {
        type: 'region_expanded', runId: 'run-region', jobId: 'job-region', nodeId: 'r',
        detail: { kind: 'map', binding: 'zip', iterations: 3 },
      },
      {
        type: 'region_finished', runId: 'run-region', jobId: 'job-region', nodeId: 'r',
        detail: { iterations: 3 },
      },
      {
        type: 'region_expanded', runId: 'run-region', jobId: 'job-region', nodeId: 'w',
        detail: { kind: 'while', binding: 'zip', iterations: null },
      },
    ])
    expect(events).toEqual([
      {
        kind: 'regionExpanded',
        execution: { connection: CONN, prompt: 'job-region' },
        timestamp: 0,
        runtimeNodeId: 'r',
        regionKind: 'map',
        binding: 'zip',
        iterations: 3,
      },
      {
        kind: 'regionFinished',
        execution: { connection: CONN, prompt: 'job-region' },
        timestamp: 0,
        runtimeNodeId: 'r',
        iterations: 3,
      },
      {
        kind: 'regionExpanded',
        execution: { connection: CONN, prompt: 'job-region' },
        timestamp: 0,
        runtimeNodeId: 'w',
        regionKind: 'while',
        binding: 'zip',
        iterations: null,
      },
    ])
  })
})

describe('dinkster stream replay: success', () => {
  const events = replay(successStream.messages)

  it('routes every execution event to (connection, jobId)', () => {
    const scoped = events.filter(isExecutionEvent)
    expect(scoped.length).toBeGreaterThan(0)
    for (const e of scoped) {
      expect(e.execution).toBeDefined()
      expect(executionKey(e.execution)).toBe(keyOf('job-1'))
    }
  })

  it('starts once and completes exactly once (run_finished + job_state dedupe)', () => {
    expect(events.filter((e) => e.kind === 'started')).toHaveLength(1)
    expect(events.filter((e) => e.kind === 'completed')).toHaveLength(1)
    const last = [...events].reverse().find((e) => e.kind !== 'status')!
    expect(last.kind).toBe('completed')
  })

  it('walks each node through running -> done via per-node state maps', () => {
    const byNode = new Map<string, NodeProgress['state'][]>()
    for (const [id, p] of nodeEntries(events)) {
      byNode.set(id, [...(byNode.get(id) ?? []), p.state])
    }
    for (const id of ['m', 'a', 'p', 'r']) {
      const states = byNode.get(id)!
      expect(states[0]).toBe('running')
      expect(states[states.length - 1]).toBe('done')
    }
  })

  it('carries per-output summaries on node_finished, length exactly for lists', () => {
    // detail.outputs (backend commit ea9ab93): {outputId: {typeId, length?}}
    // for INTERMEDIATE nodes mid-run, not just job-result targets.
    const done = new Map(nodeEntries(events).filter(([, p]) => p.state === 'done'))
    expect(done.get('r')!.outputs).toEqual({ items: { typeId: 'list<core.int>', length: 3 } })
    expect(done.get('a')!.outputs).toEqual({ out: { typeId: 'core.int', value: 8 } })
    expect(done.get('a')!.outputs!['out']).not.toHaveProperty('length')
  })

  it('normalizes progress to bounded values with max', () => {
    const progress = nodeEntries(events).filter(([, p]) => p.value !== undefined)
    expect(progress.length).toBeGreaterThan(0)
    for (const [id, p] of progress) {
      expect(id).toBe('a')
      expect(p.state).toBe('running')
      expect(p.value!).toBeGreaterThanOrEqual(0)
      expect(p.value!).toBeLessThanOrEqual(1)
      expect(p.max).toBe(2)
    }
    // Final progress step reaches 1.
    expect(progress[progress.length - 1]![1].value).toBe(1)
  })

  it('decodes the preview from a self-describing binary frame', () => {
    const previews = events.filter((e) => e.kind === 'preview')
    expect(previews).toHaveLength(1)
    const preview = previews[0]!
    if (preview.kind !== 'preview') throw new Error('unreachable')
    expect(preview.runtimeNodeId).toBe('p')
    expect(preview.channel).toBe('image/jpeg')
    expect(preview.payload).toBeInstanceOf(ArrayBuffer)
    const original = successStream.messages.find((m) => m._binary === true)!
    const expected = Uint8Array.from(atob(original._blobBase64!), (c) => c.charCodeAt(0))
    expect(new Uint8Array(preview.payload as ArrayBuffer)).toEqual(expected)
  })
})

describe('preview frame-ring metadata', () => {
  const previewMsg = (data: Record<string, unknown>): RecordedMessage => ({
    type: 'node_event', runId: 'run-ring', jobId: 'job-ring', nodeId: 'sampler',
    event: 'preview', data: { mime: 'image/jpeg', ...data },
  })
  const only = (events: NormalizedEvent[]) => {
    expect(events).toHaveLength(1)
    return events[0]! as Extract<NormalizedEvent, { kind: 'preview' }>
  }

  it('carries stream, ring addressing, and fps through normalization', () => {
    const preview = only(replay([
      previewMsg({ stream: 'video', frameIndex: 3, frameCount: 21, fps: 16 }),
    ]))
    expect(preview).toMatchObject({
      kind: 'preview',
      execution: { connection: CONN, prompt: 'job-ring' },
      runtimeNodeId: 'sampler',
      channel: 'image/jpeg',
      stream: 'video',
      frameIndex: 3,
      frameCount: 21,
      fps: 16,
    })
  })

  it.each([
    ['frameIndex >= frameCount', { frameIndex: 21, frameCount: 21 }],
    ['negative frameIndex', { frameIndex: -1, frameCount: 21 }],
    ['non-integer frameIndex', { frameIndex: 1.5, frameCount: 21 }],
    ['frameIndex without frameCount', { frameIndex: 3 }],
    ['frameCount without frameIndex', { frameCount: 21 }],
  ])('degrades a malformed ring (%s) to a plain still, keeping the frame', (_name, data) => {
    const preview = only(replay([previewMsg({ ...data, fps: 16 })]))
    expect(preview.kind).toBe('preview')
    expect(preview.frameIndex).toBeUndefined()
    expect(preview.frameCount).toBeUndefined()
    expect(preview.fps).toBeUndefined()
  })

  it.each([[0], [-8], [Number.NaN], [Number.POSITIVE_INFINITY]])(
    'drops a useless fps (%s) but keeps valid ring addressing',
    (fps) => {
      const preview = only(replay([previewMsg({ frameIndex: 0, frameCount: 4, fps })]))
      expect(preview.frameIndex).toBe(0)
      expect(preview.frameCount).toBe(4)
      expect(preview.fps).toBeUndefined()
    },
  )

  it('attaches stream even without ring addressing', () => {
    const preview = only(replay([previewMsg({ stream: 'audio' })]))
    expect(preview.stream).toBe('audio')
    expect(preview.frameIndex).toBeUndefined()
  })
})

describe('execution arm receipts', () => {
  it('retains the selected arm from start through terminal node state', () => {
    const events = replay([
      { type: 'node_started', runId: 'r-arm', jobId: 'j-arm', nodeId: 'k', detail: { executionArm: 'native' } },
      { type: 'node_finished', runId: 'r-arm', jobId: 'j-arm', nodeId: 'k', detail: { executionArm: 'native', outputs: {} } },
    ])
    expect(nodeEntries(events)).toEqual([
      ['k', { state: 'running', executionArm: 'native' }],
      ['k', { state: 'done', executionArm: 'native' }],
    ])
  })

  it('retains provider, pack, and worker attribution through terminal node state', () => {
    const events = replay([
      { type: 'node_started', runId: 'r-worker', jobId: 'j-worker', nodeId: 'k', detail: { executionArm: 'native', provider: 'vision.depth.v3', pack: 'dinkster-vision-depth-anything-v3', worker: 'render-box' } },
      { type: 'node_finished', runId: 'r-worker', jobId: 'j-worker', nodeId: 'k', detail: { executionArm: 'native', provider: 'vision.depth.v3', pack: 'dinkster-vision-depth-anything-v3', worker: 'render-box', outputs: {} } },
    ])
    expect(nodeEntries(events)).toEqual([
      ['k', { state: 'running', executionArm: 'native', provider: 'vision.depth.v3', pack: 'dinkster-vision-depth-anything-v3', worker: 'render-box' }],
      ['k', { state: 'done', executionArm: 'native', provider: 'vision.depth.v3', pack: 'dinkster-vision-depth-anything-v3', worker: 'render-box' }],
    ])
  })

  it('carries worker attribution when progress is the first observed node event', () => {
    expect(nodeEntries(replay([{
      type: 'node_event', event: 'progress', runId: 'r-progress', jobId: 'j-progress', nodeId: 'k',
      executionArm: 'comfyui', provider: 'vision.remote', pack: 'vision-pack', worker: 'remote', data: { step: 1, total: 2 },
    }]))).toEqual([['k', {
      state: 'running', executionArm: 'comfyui', provider: 'vision.remote', pack: 'vision-pack', worker: 'remote', value: 0.5, max: 2,
    }]])
  })
})

describe('dinkster stream replay: cached', () => {
  const events = replay(cachedStream.messages)

  it('marks every node cached and completes once', () => {
    const cached = nodeEntries(events).filter(([, p]) => p.state === 'cached')
    expect(new Set(cached.map(([id]) => id))).toEqual(new Set(['m', 'a', 'p', 'r']))
    expect(events.filter((e) => e.kind === 'completed')).toHaveLength(1)
    expect(events.filter((e) => e.kind === 'error')).toHaveLength(0)
  })

  it('cache hits carry the same per-output summaries as fresh finishes', () => {
    const cached = new Map(nodeEntries(events).filter(([, p]) => p.state === 'cached'))
    expect(cached.get('r')!.outputs).toEqual({ items: { typeId: 'list<core.int>', length: 3 } })
    expect(cached.get('a')!.outputs).toEqual({ out: { typeId: 'core.int', value: 8 } })
  })
})

describe('dinkster stream replay: skip cascade', () => {
  const events = replay(skipStream.messages)

  it('normalizes node_skipped to a normal skipped state with root provenance', () => {
    const skipped = nodeEntries(events).filter(([, p]) => p.state === 'skipped')
    expect(new Set(skipped.map(([id]) => id))).toEqual(new Set(['a', 'b']))
    // Both bystanders point at the ONE root origin, never each other.
    for (const [, p] of skipped) expect(p.skipOrigin).toBe('m/value')
  })

  it('produces zero error events and still completes', () => {
    expect(events.filter((e) => e.kind === 'error')).toHaveLength(0)
    expect(nodeEntries(events).filter(([, p]) => p.state === 'error')).toHaveLength(0)
    expect(events.filter((e) => e.kind === 'completed')).toHaveLength(1)
  })
})

describe('dinkster stream replay: fail-policy failure (no node_failed event)', () => {
  const events = replay(failureStream.messages)

  it('terminates with an error carrying the culprit node and message', () => {
    expect(events.filter((e) => e.kind === 'completed')).toHaveLength(0)
    const errors = events.filter((e) => e.kind === 'error')
    expect(errors).toHaveLength(1)
    const error = errors[0]!
    if (error.kind !== 'error') throw new Error('unreachable')
    expect(error.runtimeNodeId).toBe('s')
    expect(error.detail.exceptionType).toBe('execution')
    expect(error.detail.exceptionMessage).toContain("on_absent='fail'")
  })

  it('marks the culprit node error even though no node_failed was emitted', () => {
    const errorStates = nodeEntries(events).filter(([, p]) => p.state === 'error')
    expect(errorStates.map(([id]) => id)).toEqual(['s'])
    // The node that DID run still finishes normally.
    const doneStates = nodeEntries(events).filter(([, p]) => p.state === 'done')
    expect(doneStates.map(([id]) => id)).toEqual(['m'])
  })
})

describe('routing guards', () => {
  it('drops events with no job identity instead of guessing', () => {
    const normalizer = new DinksterNormalizer(CONN, () => 0)
    expect(normalizer.normalize({ type: 'node_started', nodeId: 'x' })).toEqual([])
    expect(
      normalizer.normalize({ type: 'node_started', nodeId: 'x', runId: 'never-seen' }),
    ).toEqual([])
  })

  it('resolves runId-only stragglers via prior correlation', () => {
    const normalizer = new DinksterNormalizer(CONN, () => 0)
    normalizer.normalize({ type: 'job_state', jobId: 'job-9', runId: 'run-9', state: 'running' })
    const events = normalizer.normalize({ type: 'node_started', nodeId: 'x', runId: 'run-9' }).filter(isExecutionEvent)
    expect(events).toHaveLength(1)
    expect(executionKey(events[0]!.execution)).toBe(keyOf('job-9'))
  })

  it('drops unknown event types without crashing', () => {
    const normalizer = new DinksterNormalizer(CONN, () => 0)
    expect(
      normalizer.normalize({ type: 'totally_new_kind', jobId: 'job-1', nodeId: 'x' }),
    ).toEqual([])
  })

  it('FR-4 a terminal job never emits a SECOND terminal event, in any order', () => {
    // failed -> straggling run_finished: must not read as a success reversal
    const n1 = new DinksterNormalizer(CONN, () => 0)
    expect(
      n1.normalize({ type: 'job_state', jobId: 'j', state: 'failed', error: { message: 'boom' } })
        .some((e) => e.kind === 'error'),
    ).toBe(true)
    expect(n1.normalize({ type: 'run_finished', jobId: 'j' })).toEqual([])
    // run_finished -> straggling failed/cancelled job_state: no reversal either
    const n2 = new DinksterNormalizer(CONN, () => 0)
    expect(n2.normalize({ type: 'run_finished', jobId: 'j' })).toEqual([
      expect.objectContaining({ kind: 'completed' }),
    ])
    expect(n2.normalize({ type: 'job_state', jobId: 'j', state: 'failed', error: { message: 'late' } })).toEqual([])
    expect(n2.normalize({ type: 'job_state', jobId: 'j', state: 'cancelled' })).toEqual([])
  })

  it('never cross-routes concurrent jobs interleaved on one socket', () => {
    const normalizer = new DinksterNormalizer(CONN, () => 0)
    const out: NormalizedEvent[] = []
    const a = [...successStream.messages]
    const b = [...cachedStream.messages]
    while (a.length > 0 || b.length > 0) {
      const nextA = a.shift()
      const nextB = b.shift()
      if (nextA) out.push(...normalizer.normalize(toWire(nextA)))
      if (nextB) out.push(...normalizer.normalize(toWire(nextB)))
    }
    const keys = new Map<string, string>([
      [keyOf('job-1'), 'job-1'],
      [keyOf('job-2'), 'job-2'],
    ])
    const byJob = new Map<string, NormalizedEvent[]>()
    for (const e of out) {
      if (!isExecutionEvent(e)) continue
      const jobId = keys.get(executionKey(e.execution))
      expect(jobId).toBeDefined()
      byJob.set(jobId!, [...(byJob.get(jobId!) ?? []), e])
    }
    // job-1 owns the running/done states + preview; job-2 owns all cached.
    const job1 = byJob.get('job-1')!
    const job2 = byJob.get('job-2')!
    expect(job1.filter((e) => e.kind === 'completed')).toHaveLength(1)
    expect(job2.filter((e) => e.kind === 'completed')).toHaveLength(1)
    expect(nodeEntries(job1).some(([, p]) => p.state === 'cached')).toBe(false)
    expect(nodeEntries(job2).every(([, p]) => p.state === 'cached')).toBe(true)
    expect(job1.filter((e) => e.kind === 'preview')).toHaveLength(1)
    expect(job2.filter((e) => e.kind === 'preview')).toHaveLength(0)
  })

  it('emits per-connection queue depth from queue_state', () => {
    const normalizer = new DinksterNormalizer(CONN, () => 0)
    const events = normalizer.normalize({ type: 'queue_state', queued: 3, running: 1 })
    expect(events).toEqual([
      { kind: 'status', connection: CONN, timestamp: 0, queueRemaining: 3 },
    ])
  })
})

describe('curve histogram previews', () => {
  const histogram = Array.from({ length: 256 }, (_, index) => index)

  it('normalizes an exact attributed histogram onto its own preview stream', () => {
    expect(new DinksterNormalizer(CONN, () => 23).normalize({
      type: 'node_event', jobId: 'curve-job', nodeId: 'curve',
      event: 'dinkster.curve.histogram', data: { histogram },
    })).toEqual([{
      kind: 'preview',
      execution: { connection: CONN, prompt: asPromptId('curve-job') },
      timestamp: 23,
      runtimeNodeId: 'curve',
      channel: 'application/vnd.dinkster.curve-histogram+json',
      payload: { histogram },
      stream: 'curve-histogram',
    }])
  })

  it.each([
    { histogram: histogram.slice(1) },
    { histogram: [...histogram.slice(0, -1), -1] },
    { histogram: [...histogram.slice(0, -1), 1.5] },
    { histogram, extra: true },
  ])('rejects malformed histogram data', (data) => {
    const malformed: string[] = []
    const normalizer = new DinksterNormalizer(CONN, () => 0, (detail) => malformed.push(detail))
    expect(normalizer.normalize({
      type: 'node_event', jobId: 'curve-job', nodeId: 'curve',
      event: 'dinkster.curve.histogram', data,
    })).toEqual([])
    expect(malformed).toEqual(['node_event dinkster.curve.histogram with malformed data'])
  })
})

describe('compositor state previews', () => {
  const digest = `blake3:${'a'.repeat(64)}`
  const state = {
    version: 2,
    document: {
      format: 'dinkster-image', formatVersion: 2, lineage: 'event-compositor',
      canvas: { width: 64, height: 48, colorSpace: 'srgb', channelDepth: 8, compositing: 'premultiplied-alpha' },
      allocation: { nextOrdinal: 2 }, rootLayerIds: ['l0'],
      layers: { l0: {
        id: 'l0', kind: 'raster', name: 'Layer 1', visible: true, opacity: 65_535,
        transform: { a: 1_000_000, b: 0, c: 0, d: 1_000_000, tx: 0, ty: 0, components: {
          x: 0, y: 0, width: 64, height: 48, rotation: 0, flipHorizontal: false, flipVertical: false,
          sourceWidth: 64, sourceHeight: 48,
        } }, blendMode: 'normal', clipping: 'none', maskIds: [], resourceId: 'r1',
        sourceRect: { x: 0, y: 0, width: 64, height: 48 },
      } },
      masks: {}, resources: { r1: {
        id: 'r1', kind: 'raster', digest, byteSize: 1, mediaType: 'image/png', width: 64, height: 48,
        colorSpace: 'srgb', channelDepth: 8, alphaMode: 'straight',
      } },
    },
    documentDigest: digest,
    stale: false,
    layerStreams: ['compositor.layer.0'],
  }

  it('normalizes exact state onto its own attributed preview stream', () => {
    expect(new DinksterNormalizer(CONN, () => 29).normalize({
      type: 'node_event', jobId: 'compositor-job', nodeId: 'compositor',
      event: 'dinkster.compositor.state', data: state,
    })).toEqual([{
      kind: 'preview',
      execution: { connection: CONN, prompt: asPromptId('compositor-job') },
      timestamp: 29,
      runtimeNodeId: 'compositor',
      channel: 'application/vnd.dinkster.compositor-state+json',
      payload: compositorStateOf(state),
      stream: 'compositor-state',
    }])
  })

  it.each([
    { ...state, extra: true },
    { ...state, stale: 'false' },
    { ...state, layerStreams: ['compositor.layer.1'] },
  ])('rejects malformed state data', (data) => {
    const malformed: string[] = []
    const normalizer = new DinksterNormalizer(CONN, () => 0, (detail) => malformed.push(detail))
    expect(normalizer.normalize({
      type: 'node_event', jobId: 'compositor-job', nodeId: 'compositor',
      event: 'dinkster.compositor.state', data,
    })).toEqual([])
    expect(malformed).toEqual(['node_event dinkster.compositor.state with malformed data'])
  })

  it('rejects compositor state carried by a binary frame', () => {
    const malformed: string[] = []
    const normalizer = new DinksterNormalizer(CONN, () => 0, (detail) => malformed.push(detail))
    const header = JSON.stringify({
      type: 'node_event', jobId: 'compositor-job', nodeId: 'compositor',
      event: 'dinkster.compositor.state', data: state,
    })
    const head = new TextEncoder().encode(header)
    const wire = new Uint8Array(4 + head.length + 1)
    new DataView(wire.buffer).setUint32(0, head.length, false)
    wire.set(head, 4)
    wire[wire.length - 1] = 1
    expect(normalizer.normalize(wire.buffer)).toEqual([])
    expect(malformed).toEqual(['node_event dinkster.compositor.state with malformed data'])
  })
})

describe('GLSL state previews', () => {
  const state = {
    width: 64,
    height: 48,
    inputs: [{ name: 'u_image1', stream: 'glsl-input-u_image1' }],
    floats: { u_float0: 0.25 },
    ints: { u_int0: 2 },
    bools: { u_bool0: true },
    curves: { u_curve0: Array.from({ length: 256 }, (_, index) => index / 255) },
  }

  it('normalizes exact state onto its own attributed preview stream', () => {
    expect(new DinksterNormalizer(CONN, () => 31).normalize({
      type: 'node_event', jobId: 'glsl-job', nodeId: 'glsl',
      event: 'dinkster.glsl.state', data: state,
    })).toEqual([{
      kind: 'preview',
      execution: { connection: CONN, prompt: asPromptId('glsl-job') },
      timestamp: 31,
      runtimeNodeId: 'glsl',
      channel: 'application/vnd.dinkster.glsl-state+json',
      payload: state,
      stream: 'glsl-state',
    }])
  })

  it.each([
    { ...state, extra: true },
    { ...state, inputs: [] },
    { ...state, curves: { u_curve0: [0, 1] } },
  ])('rejects malformed state data', (data) => {
    const malformed: string[] = []
    const normalizer = new DinksterNormalizer(CONN, () => 0, (detail) => malformed.push(detail))
    expect(normalizer.normalize({
      type: 'node_event', jobId: 'glsl-job', nodeId: 'glsl',
      event: 'dinkster.glsl.state', data,
    })).toEqual([])
    expect(malformed).toEqual(['node_event dinkster.glsl.state with malformed data'])
  })

  it('rejects GLSL state carried by a binary frame', () => {
    const malformed: string[] = []
    const normalizer = new DinksterNormalizer(CONN, () => 0, (detail) => malformed.push(detail))
    const header = JSON.stringify({
      type: 'node_event', jobId: 'glsl-job', nodeId: 'glsl',
      event: 'dinkster.glsl.state', data: state,
    })
    const head = new TextEncoder().encode(header)
    const wire = new Uint8Array(4 + head.length + 1)
    new DataView(wire.buffer).setUint32(0, head.length, false)
    wire.set(head, 4)
    wire[wire.length - 1] = 1
    expect(normalizer.normalize(wire.buffer)).toEqual([])
    expect(malformed).toEqual(['node_event dinkster.glsl.state with malformed data'])
  })
})

describe('non-semantic node activity', () => {
  const normalize = (message: DinksterRawJson): readonly NormalizedEvent[] =>
    new DinksterNormalizer(CONN, () => 17).normalize(message)

  it('normalizes lazy_demand detail without claiming branch or execution semantics', () => {
    expect(normalize({
      type: 'node_event',
      jobId: 'job-lazy',
      runId: 'run-lazy',
      nodeId: 'switch',
      event: 'lazy_demand',
      data: {
        round: 2,
        status: 'waiting',
        requestedInputs: ['on_true', 'on_false'],
        newInputs: ['on_false'],
        demandedInputs: ['on_true', 'on_false'],
        producerNodes: ['producer-b'],
      },
    })).toEqual([{
      kind: 'activity',
      execution: { connection: CONN, prompt: asPromptId('job-lazy') },
      timestamp: 17,
      activity: {
        kind: 'lazy_demand',
        nodeId: 'switch',
        round: 2,
        status: 'waiting',
        requestedInputs: ['on_true', 'on_false'],
        newInputs: ['on_false'],
        demandedInputs: ['on_true', 'on_false'],
        producerNodes: ['producer-b'],
      },
    }])
  })

  it('normalizes cache_miss detail while omitting its cache key', () => {
    const events = normalize({
      type: 'cache_miss',
      jobId: 'job-cache',
      runId: 'run-cache',
      nodeId: 'sampler',
      detail: {
        cache_key: 'secret-opaque-key',
        reason: 'inputs-changed',
        changed_inputs: ['seed'],
        added_inputs: ['control'],
        removed_inputs: ['legacy'],
      },
    })
    expect(events).toEqual([{
      kind: 'activity',
      execution: { connection: CONN, prompt: asPromptId('job-cache') },
      timestamp: 17,
      activity: {
        kind: 'cache_miss',
        nodeId: 'sampler',
        reason: 'inputs-changed',
        changedInputs: ['seed'],
        addedInputs: ['control'],
        removedInputs: ['legacy'],
      },
    }])
    expect(JSON.stringify(events)).not.toContain('secret-opaque-key')
  })

  it.each([
    ['lazy missing node', { type: 'node_event', jobId: 'j', event: 'lazy_demand', data: { round: 1, status: 'ready', requestedInputs: [], newInputs: [], demandedInputs: [], producerNodes: [] } }],
    ['lazy malformed round', { type: 'node_event', jobId: 'j', nodeId: 'n', event: 'lazy_demand', data: { round: 1.5, status: 'ready', requestedInputs: [], newInputs: [], demandedInputs: [], producerNodes: [] } }],
    ['lazy malformed list', { type: 'node_event', jobId: 'j', nodeId: 'n', event: 'lazy_demand', data: { round: 1, status: 'ready', requestedInputs: 'input', newInputs: [], demandedInputs: [], producerNodes: [] } }],
    ['cache missing detail', { type: 'cache_miss', jobId: 'j', nodeId: 'n' }],
    ['cache missing key', { type: 'cache_miss', jobId: 'j', nodeId: 'n', detail: { reason: 'first-seen' } }],
    ['cache malformed key', { type: 'cache_miss', jobId: 'j', nodeId: 'n', detail: { cache_key: 7, reason: 'first-seen' } }],
    ['cache malformed reason', { type: 'cache_miss', jobId: 'j', nodeId: 'n', detail: { cache_key: 'key', reason: 7 } }],
  ])('drops malformed activity: %s', (_label, message) => {
    expect(normalize(message as DinksterRawJson)).toEqual([])
  })

  it('bounds retained activity strings and lists', () => {
    const long = 'x'.repeat(200)
    const names = Array.from({ length: 20 }, (_, index) => `${index}-${long}`)
    const [event] = normalize({
      type: 'node_event',
      jobId: 'j',
      nodeId: 'bounded-node',
      event: 'lazy_demand',
      data: {
        round: 1,
        status: 'waiting',
        requestedInputs: names,
        newInputs: names,
        demandedInputs: names,
        producerNodes: names,
      },
    })
    expect(event?.kind).toBe('activity')
    if (event?.kind !== 'activity' || event.activity.kind !== 'lazy_demand') return
    expect(event.activity.nodeId).toBe('bounded-node')
    expect(event.activity.requestedInputs).toHaveLength(16)
    expect(event.activity.requestedInputs.every((name) => name.length <= 128)).toBe(true)
  })

  it('keeps unknown event kinds silent and forwards unknown node event names opaquely', () => {
    expect(normalize({ type: 'future_activity', jobId: 'j', nodeId: 'n' })).toEqual([])
    expect(normalize({ type: 'node_event', jobId: 'j', nodeId: 'n', event: 'future.activity', data: { value: 7 } })).toEqual([{
      kind: 'node.event',
      execution: { connection: CONN, prompt: 'j' },
      timestamp: 17,
      name: 'future.activity',
      payload: { value: 7 },
      runtimeNodeId: 'n',
    }])
  })
})

describe('job failure error hints', () => {
  const failureDetail = (hints?: unknown) => {
    const normalizer = new DinksterNormalizer(CONN, () => 0)
    const events = normalizer.normalize({
      type: 'job_state',
      jobId: 'hinted-job',
      state: 'failed',
      error: {
        kind: 'execution',
        message: 'expected scalar type Half but found Float',
        traceback: 'raw line one\nraw line two',
        ...(hints !== undefined ? { hints } : {}),
      },
    })
    const event = events.find((candidate) => candidate.kind === 'error')
    if (event?.kind !== 'error') throw new Error('expected an error event')
    return event.detail
  }

  it('decodes hints with and without suggestions without client-side recapping', () => {
    const detail = failureDetail([
      {
        code: 'dtype-mismatch',
        message: 'Input dtype Float does not match required dtype Half.',
      },
      {
        code: 'tensor-shape-mismatch',
        message: 'Tensor dimensions do not match.',
        suggestion: 'Try permuting the input layout.',
      },
      { code: 'device-mismatch', message: 'Inputs are on different devices.' },
      { code: 'cuda-oom', message: 'CUDA ran out of memory.' },
    ])

    expect(detail.exceptionMessage).toBe('expected scalar type Half but found Float')
    expect(detail.traceback).toEqual(['raw line one', 'raw line two'])
    expect(detail.hints).toEqual([
      {
        code: 'dtype-mismatch',
        message: 'Input dtype Float does not match required dtype Half.',
      },
      {
        code: 'tensor-shape-mismatch',
        message: 'Tensor dimensions do not match.',
        suggestion: 'Try permuting the input layout.',
      },
      { code: 'device-mismatch', message: 'Inputs are on different devices.' },
      { code: 'cuda-oom', message: 'CUDA ran out of memory.' },
    ])
  })

  it.each([
    ['absent', undefined],
    ['empty', []],
    ['non-array', { code: 'cuda-oom', message: 'CUDA ran out of memory.' }],
    ['wrong scalar type', 'cuda-oom'],
  ])('omits hints for an %s hints field', (_label, hints) => {
    expect(failureDetail(hints)).not.toHaveProperty('hints')
  })

  it('drops malformed entries individually and ignores malformed optional suggestions', () => {
    expect(failureDetail([
      null,
      { message: 'missing code' },
      { code: 'device-mismatch' },
      { code: 1, message: 'non-string code' },
      { code: 'cuda-oom', message: 2 },
      { code: 'dtype-mismatch', message: 'Valid hint.', suggestion: false },
    ]).hints).toEqual([
      { code: 'dtype-mismatch', message: 'Valid hint.' },
    ])
  })

  it('ignores unknown extra keys while preserving a valid hint', () => {
    expect(failureDetail([
      {
        code: 'tensor-shape-mismatch',
        message: 'Tensor dimensions do not match.',
        suggestion: 'Try permuting the input layout.',
        futureMetadata: { confidence: 0.9 },
      },
    ]).hints).toEqual([
      {
        code: 'tensor-shape-mismatch',
        message: 'Tensor dimensions do not match.',
        suggestion: 'Try permuting the input layout.',
      },
    ])
  })
})

describe('connection-level control events (schema epochs, composition)', () => {
  const n = () => new DinksterNormalizer(CONN, () => 5)

  it('maps schema_changed to a connection-scoped epoch ping', () => {
    expect(n().normalize({ type: 'schema_changed', epoch: 2 })).toEqual([
      { kind: 'schemaChanged', connection: CONN, timestamp: 5, epoch: 2 },
    ])
  })

  it('drops a schema_changed ping without an epoch', () => {
    expect(n().normalize({ type: 'schema_changed' })).toEqual([])
  })

  it('maps composition_progress, phase omitted-when-absent', () => {
    expect(n().normalize({ type: 'composition_progress', done: 2, total: 5, phase: 'packs' })).toEqual([
      { kind: 'compositionProgress', connection: CONN, timestamp: 5, done: 2, total: 5, phase: 'packs' },
    ])
    expect(n().normalize({ type: 'composition_progress', done: 2, total: 5 })).toEqual([
      { kind: 'compositionProgress', connection: CONN, timestamp: 5, done: 2, total: 5 },
    ])
    expect(n().normalize({ type: 'composition_progress', done: 2 })).toEqual([])
  })

  it('maps composition_complete, defaulting the failed list to empty', () => {
    expect(n().normalize({ type: 'composition_complete', epoch: 3 })).toEqual([
      { kind: 'compositionComplete', connection: CONN, timestamp: 5, epoch: 3, failed: [] },
    ])
    expect(n().normalize({ type: 'composition_complete', epoch: 3, failed: ['bad.pack'] })).toEqual([
      { kind: 'compositionComplete', connection: CONN, timestamp: 5, epoch: 3, failed: ['bad.pack'] },
    ])
  })

  it('maps pack_failed with its error line', () => {
    expect(n().normalize({ type: 'pack_failed', pack: 'vhs.video', error: 'boom' })).toEqual([
      { kind: 'packFailed', connection: CONN, timestamp: 5, pack: 'vhs.video', error: 'boom' },
    ])
    expect(n().normalize({ type: 'pack_failed', error: 'boom' })).toEqual([])
  })

  it('control events carry no execution identity', () => {
    const events = [
      ...n().normalize({ type: 'schema_changed', epoch: 2 }),
      ...n().normalize({ type: 'composition_progress', done: 1, total: 2 }),
      ...n().normalize({ type: 'composition_complete', epoch: 2 }),
      ...n().normalize({ type: 'pack_failed', pack: 'p', error: 'e' }),
    ]
    expect(events).toHaveLength(4)
    for (const e of events) expect(isExecutionEvent(e)).toBe(false)
  })
})

describe('decodeDinksterBinaryFrame edge cases', () => {
  it('rejects frames shorter than the length prefix', () => {
    expect(decodeDinksterBinaryFrame(new Uint8Array([0, 0]).buffer)).toBeUndefined()
  })

  it('rejects a header length pointing past the frame end', () => {
    const frame = new Uint8Array(8)
    new DataView(frame.buffer).setUint32(0, 100, false)
    expect(decodeDinksterBinaryFrame(frame.buffer)).toBeUndefined()
  })

  it('rejects malformed JSON headers and headers without type', () => {
    const make = (headerText: string): ArrayBuffer => {
      const header = new TextEncoder().encode(headerText)
      const frame = new Uint8Array(4 + header.length)
      new DataView(frame.buffer).setUint32(0, header.length, false)
      frame.set(header, 4)
      return frame.buffer
    }
    expect(decodeDinksterBinaryFrame(make('{not json'))).toBeUndefined()
    expect(decodeDinksterBinaryFrame(make('{"noType":true}'))).toBeUndefined()
  })

  it('normalize drops undecodable binary frames without crashing', () => {
    const normalizer = new DinksterNormalizer(CONN, () => 0)
    expect(normalizer.normalize(new Uint8Array([1, 2, 3]).buffer)).toEqual([])
  })
})

describe('completed-job hydration (nodeStatesFromDinksterJob)', () => {
  it('reconstructs the success job as done, with output summaries for targets', () => {
    // Job-result descriptors cover TARGET nodes only (p, r); intermediates
    // get their summaries from the live event stream, not hydration.
    expect(nodeStatesFromDinksterJob(successStream.job)).toEqual({
      m: { state: 'done' },
      a: { state: 'done' },
      p: { state: 'done', outputs: { out: { typeId: 'core.int' } } },
      r: { state: 'done', outputs: { items: { typeId: 'list<core.int>', length: 3 } } },
    })
  })

  it('reconstructs cached and skipped states from the live nodeStates map', () => {
    expect(nodeStatesFromDinksterJob(cachedStream.job)).toEqual({
      m: { state: 'cached' },
      a: { state: 'cached' },
      p: { state: 'cached', outputs: { out: { typeId: 'core.int' } } },
      r: { state: 'cached', outputs: { items: { typeId: 'list<core.int>', length: 3 } } },
    })
    expect(nodeStatesFromDinksterJob(skipStream.job)).toEqual({
      m: { state: 'done' },
      a: { state: 'skipped' },
      b: { state: 'skipped' },
    })
  })

  it('marks the failed job culprit error even without a terminal node state', () => {
    expect(nodeStatesFromDinksterJob(failureStream.job)).toEqual({
      m: { state: 'done' },
      s: { state: 'error' },
    })
  })

  it('falls back to executed/cached/skipped arrays when nodeStates is absent', () => {
    const job: DinksterJobWire = {
      state: 'completed',
      executed: ['a'],
      cached: ['b'],
      skipped: ['c'],
    }
    expect(nodeStatesFromDinksterJob(job)).toEqual({
      a: { state: 'done' },
      b: { state: 'cached' },
      c: { state: 'skipped' },
    })
  })

  it('ignores unknown state strings and non-string ids', () => {
    expect(
      nodeStatesFromDinksterJob({
        state: 'completed',
        nodeStates: { a: 'completed', b: 'weird', c: 7 },
      }),
    ).toEqual({ a: { state: 'done' } })
    expect(
      nodeStatesFromDinksterJob({ state: 'completed', executed: ['a', 5], skipped: 'nope' }),
    ).toEqual({ a: { state: 'done' } })
  })
})

describe('malformed known events report through onMalformed (R2-6)', () => {
  const collect = () => {
    const reports: string[] = []
    const normalizer = new DinksterNormalizer(CONN, () => 0, (detail) => reports.push(detail))
    return { normalizer, reports }
  }

  it('reports connection-level control events with missing required fields', () => {
    const { normalizer, reports } = collect()
    expect(normalizer.normalize({ type: 'schema_changed' })).toEqual([])
    expect(normalizer.normalize({ type: 'composition_progress', done: 2 })).toEqual([])
    expect(normalizer.normalize({ type: 'composition_complete' })).toEqual([])
    expect(normalizer.normalize({ type: 'pack_failed', error: 'boom' })).toEqual([])
    expect(reports).toHaveLength(4)
    expect(reports[0]).toContain('schema_changed')
  })

  it('reports a known job event carrying no job identity at all', () => {
    const { normalizer, reports } = collect()
    expect(normalizer.normalize({ type: 'node_started', nodeId: 'x' })).toEqual([])
    expect(reports).toHaveLength(1)
    expect(reports[0]).toContain('node_started')
  })

  it('reports node events missing a nodeId and node_event without a name', () => {
    const { normalizer, reports } = collect()
    expect(normalizer.normalize({ type: 'node_started', jobId: 'j1' })).toEqual([])
    expect(normalizer.normalize({ type: 'node_event', jobId: 'j1', event: 'progress', data: { step: 1, total: 2 } })).toEqual([])
    expect(normalizer.normalize({ type: 'node_event', jobId: 'j1', nodeId: 'x' })).toEqual([])
    expect(reports).toHaveLength(3)
  })

  it('reports a job_state outside the state vocabulary', () => {
    const { normalizer, reports } = collect()
    expect(normalizer.normalize({ type: 'job_state', jobId: 'j1', state: 'explodinated' })).toEqual([])
    expect(normalizer.normalize({ type: 'job_state', jobId: 'j1' })).toEqual([])
    expect(reports).toHaveLength(2)
    expect(reports[0]).toContain("'explodinated'")
  })

  it('reports an undecodable binary frame fed directly to normalize', () => {
    const { normalizer, reports } = collect()
    expect(normalizer.normalize(new Uint8Array([1, 2]).buffer)).toEqual([])
    expect(reports).toHaveLength(1)
    expect(reports[0]).toContain('binary')
  })

  it('never reports unroutable stragglers, unknown kinds, or benign transitions', () => {
    const { normalizer, reports } = collect()
    // runId-only straggler with no prior correlation: legitimate after a
    // reload, silent by design.
    expect(normalizer.normalize({ type: 'node_started', nodeId: 'x', runId: 'never-seen' })).toEqual([])
    // Unknown kinds are forward compatibility, with or without identity.
    expect(normalizer.normalize({ type: 'totally_new_kind', jobId: 'j1' })).toEqual([])
    expect(normalizer.normalize({ type: 'totally_new_kind' })).toEqual([])
    // queued/running job transitions carry no meaning here.
    expect(normalizer.normalize({ type: 'job_state', jobId: 'j1', state: 'queued' })).toEqual([])
    expect(normalizer.normalize({ type: 'job_state', jobId: 'j1', state: 'running' })).toEqual([])
    // Routed node events are forwarded, while an event without execution
    // identity remains unroutable and silent.
    expect(normalizer.normalize({ type: 'node_event', jobId: 'j1', nodeId: 'x', event: 'my.pack.event' })).toHaveLength(1)
    expect(normalizer.normalize({ type: 'node_event', event: 'my.pack.event', data: {} })).toEqual([])
    // queue_state without a queued count still emits a bare status event.
    expect(normalizer.normalize({ type: 'queue_state' })).toHaveLength(1)
    expect(reports).toEqual([])
  })
})
